name: Build Photino.Native

on:
  push:
    branches:
      - tmp
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libnotify-dev

      - name: Create output directory
        run: mkdir -p x64/Release

      - name: Build Photino.Native.so
        run: |
          gcc -std=c++11 -shared -DOS_LINUX \
            Photino.Native/Exports.cpp Photino.Native/Photino.Linux.cpp \
            -o x64/Release/Photino.Native.so \
            `pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.1 libnotify` -fPIC

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Photino.Native.so
          path: x64/Release/Photino.Native.so

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install WIL via vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg.exe install wil:x64-windows

      - name: Install WebView2 SDK via NuGet
        run: |
          nuget install Microsoft.Web.WebView2 -Version 1.0.3351.48 -OutputDirectory webview2sdk

      - name: Create output directory
        run: mkdir x64\Release

      - name: Build Photino.Native.dll
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
          cl /LD /EHsc /std:c++17 /D OS_WINDOWS ^
            Photino.Native\Exports.cpp Photino.Native\Photino.Windows.cpp ^
            /I vcpkg\packages\wil_x64-windows\include ^
            /I webview2sdk\Microsoft.Web.WebView2.1.0.3351.48\build\native\include ^
            /Fe:x64\Release\Photino.Native.dll
        shell: cmd

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p x64/Release

      - name: Build Photino.Native.dylib
        run: |
          clang++ -std=c++11 -dynamiclib -DOS_MACOS \
            Photino.Native/Exports.cpp \
            Photino.Native/Photino.Mac.mm \
            Photino.Native/Photino.Mac.AppDelegate.mm \
            Photino.Native/Photino.Mac.UiDelegate.mm \
            Photino.Native/Photino.Mac.UrlSchemeHandler.mm \
            -o x64/Release/Photino.Native.dylib \
            -framework Cocoa -framework WebKit

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Photino.Native.dylib
          path: x64/Release/Photino.Native.dylib
