name: Build Photino.Native on Linux

on:
  push:
    branches: [ tmp ]
  pull_request:
    branches: [ tmp ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libgtk-3-dev libwebkit2gtk-4.1-dev libnotify-dev

    - name: Build Photino.Native.so
      run: |
        mkdir -p x64/Release
        gcc -std=c++11 -shared -DOS_LINUX \
          Exports.cpp Photino.Linux.cpp -o x64/Release/Photino.Native.so \
          `pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.1 libnotify` -fPIC

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Photino.Native.so
        path: x64/Release/Photino.Native.so
