name: Build Photino.Native (Linux)

on:
  push:
    branches: [ tmp ]
  pull_request:
    branches: [ tmp ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev \
          libnotify-dev \
          pkg-config \
          gcc g++

    - name: Create output directory
      run: mkdir -p x64/Release

    - name: Build Photino.Native.so
      run: |
        gcc -std=c++11 -shared -DOS_LINUX \
          Photino.Native/Exports.cpp Photino.Native/Photino.Linux.cpp \
          -o x64/Release/Photino.Native.so \
          `pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.1 libnotify` -fPIC

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Photino.Native.so
        path: x64/Release/Photino.Native.so
